name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

Hi,
My name is Sebastian and I am new here, I have just started programming, take some courses at the upper secondary level which are distance.

I would have been incredibly grateful if someone could point me in the right direction.

Have an awesome time

/ S
